services:
  db:
    image: mariadb:10.6
    container_name: techchallenge-db
    restart: always
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "3386:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/conf/my.cnf:/etc/mysql/conf.d/my.cnf

    networks:
      - techchallenge-network

<<<<<<< HEAD
# <<<<<<< HEAD
=======
#<<<<<<< HEAD
>>>>>>> 058aae6f9f06762d12879c0f93c27b1f6500a1c0
  # app:
  #  depends_on:
  #    - db
  #  build: ./tomcat-build
  #  image: tomcat:9-jre8
  #  ports:
  #    - "8080:8080"
  #  volumes:
  #    - ./tomcat/webapps/:/usr/local/tomcat/webapps/
  #    - ./tomcat/logs/:/usr/local/tomcat/logs/
<<<<<<< HEAD
# =======
=======

>>>>>>> 058aae6f9f06762d12879c0f93c27b1f6500a1c0
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: techchallenge-app
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/techchallenge?useSSL=false
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    networks:
      - techchallenge-network
<<<<<<< HEAD
# >>>>>>> 0965a76c0880cf3cbe6bd2f2b6d235ab52e0284f
=======
#>>>>>>> 0965a76c0880cf3cbe6bd2f2b6d235ab52e0284f
>>>>>>> 058aae6f9f06762d12879c0f93c27b1f6500a1c0

networks:
  techchallenge-network:
    driver: bridge

volumes:
  mariadb_data:
