services:
  db:
    image: mariadb:10.6
    container_name: techchallenge-db
    restart: always
    environment:
      MARIADB_DATABASE: 'techchallenge'
      MARIADB_USER: 'admin'
      MARIADB_PASSWORD: 'noTnZQMVikRVQ6XKSJHgVaRO'
      MARIADB_ROOT_PASSWORD: 'senha_super_segura_para_o_root'
    ports:
      - "3386:3386"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/conf/my.cnf:/etc/mysql/conf.d/my.cnf

    networks:
      - techchallenge-network

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: techchallenge-app
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3386/techchallenge?useSSL=false
      SPRING_DATASOURCE_USERNAME: 'admin'
      SPRING_DATASOURCE_PASSWORD: 'noTnZQMVikRVQ6XKSJHgVaRO'
      SPRING_JPA_HIBERNATE_DDL_AUTO: 'update'
    networks:
      - techchallenge-network

networks:
  techchallenge-network:
    driver: bridge

volumes:
  mariadb_data: